name: workmanager_example
description: Demonstrates how to use the workmanager plugin.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  path_provider: ^2.0.11
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  workmanager:
    path: ../

flutter:
  uses-material-design: true